hooks:
  all:
    pre:
      - type: oidc
        provider: aws
        role_arn: "arn:aws:iam::017777978390:role/terrateam"       
workflows:
  - tag_query: "dir:policy-check"
    plan:
      - type: init
      - type: plan
      - type: run
        cmd: ['opa', 'eval', '--input=tfplan.json', '--format', 'pretty', '--data=main.rego', 'data.terraform.s3.deny']
        capture_output: true

